// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squrl.App.Data;

#nullable disable

namespace Squrl.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260505091036_AddQuantityAndLocationsToItems")]
    partial class AddQuantityAndLocationsToItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Squrl.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("locations");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<string>("UomId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_items_uom_id");

                    b.HasIndex("Name", "Description")
                        .HasDatabaseName("ix_items_name_description");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Squrl.Models.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measures");

                    b.HasIndex("Unit", "Description")
                        .HasDatabaseName("ix_unit_of_measures_unit_description");

                    b.ToTable("unit_of_measures", (string)null);
                });

            modelBuilder.Entity("Squrl.Models.Item", b =>
                {
                    b.HasOne("Squrl.Models.UnitOfMeasure", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_unit_of_measures_uom_id");

                    b.Navigation("Uom");
                });
#pragma warning restore 612, 618
        }
    }
}
