// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squrl.App.Data;

#nullable disable

namespace Squrl.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Squrl.App.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("Locations")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("locations");

                    b.Property<decimal?>("LowQuantityAlertThreshold")
                        .HasColumnType("TEXT")
                        .HasColumnName("low_quantity_alert_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UomId")
                        .HasColumnType("TEXT")
                        .HasColumnName("uom_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_items_date_created");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_items_name");

                    b.HasIndex("UomId")
                        .HasDatabaseName("ix_items_uom_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Squrl.App.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("DateOrdered")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date_ordered");

                    b.Property<string>("DateRequired")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_required");

                    b.Property<string>("DateShipped")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_shipped");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_purchase_orders_date_created");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Squrl.App.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<int>("LineSequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_sequence");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_details");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_purchase_order_details_date_created");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_purchase_order_details_item_id");

                    b.HasIndex("PurchaseOrderId", "LineSequence")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_order_details_purchase_order_id_line_sequence");

                    b.ToTable("purchase_order_details", null, t =>
                        {
                            t.HasCheckConstraint("CK_purchase_order_details_line_sequence", "line_sequence >= 1");
                        });
                });

            modelBuilder.Entity("Squrl.App.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_suppliers_date_created");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_suppliers_name");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Squrl.App.Models.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measures");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("ix_unit_of_measures_date_created");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_unit_of_measures_name");

                    b.ToTable("unit_of_measures", (string)null);
                });

            modelBuilder.Entity("Squrl.App.Models.Item", b =>
                {
                    b.HasOne("Squrl.App.Models.UnitOfMeasure", "Uom")
                        .WithMany()
                        .HasForeignKey("UomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_unit_of_measures_uom_id");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("Squrl.App.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Squrl.App.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_purchase_orders_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Squrl.App.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("Squrl.App.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_details_items_item_id");

                    b.HasOne("Squrl.App.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_details_purchase_orders_purchase_order_id");

                    b.Navigation("Item");

                    b.Navigation("PurchaseOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
