; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Squrl"
#define MyAppVersion "0.2.1-alpha"
#define MyAppExeName "Squrl.WindowsHost.exe"
#define OutputFileName "squrl"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{683FD8B1-94BF-49AD-98B8-1B3FDDEF9834}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequired=admin
OutputDir=..\artifacts
OutputBaseFilename={#OutputFileName}-{#MyAppVersion}-win-x64
SolidCompression=yes
WizardStyle=modern dynamic

[Dirs]
Name: "{commonappdata}\{#MyAppName}"
Name: "{commonappdata}\{#MyAppName}\Uploads"
Name: "{commonappdata}\{#MyAppName}\Logs"
Name: "{commonappdata}\{#MyAppName}\Backups"

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Work\Desktop\Projects\Squrl\publish\windows\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

Source: "C:\Users\Work\Desktop\Projects\Squrl\publish\windows\*"; \
  DestDir: "{app}"; \
  Excludes: "*.pdb,*.xml,appsettings.json,appsettings.*.json,*.db"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

Source: "appsettings.Template.json"; \
  DestDir: "{commonappdata}\{#MyAppName}"; \
  DestName: "appsettings.json"; \
  Flags: onlyifdoesntexist
    
[Code]
var ConfigCreated: Boolean;

function InitializeSetup(): Boolean;
  begin
    // Remember whether we're creating the config for the first time.
    ConfigCreated := not FileExists(
      ExpandConstant('{commonappdata}\{#MyAppName}\appsettings.json'));

      Result := True;
  end;

procedure ModifyAppSettings;
  var
    FileName: string;
    UnicodeJson: string;
    AnsiJson: AnsiString;
    ConnString: string;
  begin
    FileName := ExpandConstant('{commonappdata}\{#MyAppName}\appsettings.json');

    if LoadStringFromFile(FileName, AnsiJson) then
      begin
        UnicodeJson := string(AnsiJson);
    
        ConnString := 'Data Source=' + ExpandConstant('{commonappdata}\{#MyAppName}\squrl.db');

        StringChangeEx(ConnString, '\', '\\', True);

        if StringChangeEx(
          UnicodeJson,
          '__CONNECTION_STRING__',
          ConnString,
          True) > 0 then
          begin
            SaveStringToFile(FileName, AnsiString(UnicodeJson), False);
          end;
      end;
  end;

procedure CurStepChanged(CurStep: TSetupStep);
  begin
    if (CurStep = ssPostInstall) and ConfigCreated then
      ModifyAppSettings;
  end;

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "netsh"; \
  Parameters: "advfirewall firewall add rule name=""squrl"" dir=in action=allow protocol=TCP localport=33600"; \
  Flags: runhidden waituntilterminated

Filename: "{app}\{#MyAppExeName}"; \
  Description: "Launch Squrl"; \
  Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "netsh"; \
  Parameters: "advfirewall firewall delete rule name=""squrl"""; \
  RunOnceId: "DeleteSqurlFirewallRule"; \
  Flags: runhidden waituntilterminated